server:
  port: 80
  compression:
    enabled: true
    min-response-size: 512KB
    mime-types:
      - text/html
      - application/json
#兼容swagger配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxxxx:3306/kwan?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: xxxxxx

#csdn设置
csdn:
  self_user_name: "xxxx"  #自己的用户id
  self_user_nick_name: "xxxx"  #自己的昵称
  self_folder_id: 34345345  #自己的收藏夹id
  auto_add_view_count: 2000  #刷浏览量数量
  auto_comment_count: 40  #评论个数
  #自己的评论
  self_comment: xxxxxx;xxxxxx;xxxxxx;xxxxxx
  #自动评论
  self_reply: xxxxxx;xxxxxx;xxxxxx;xxxxxx
  #cookie
  cookie: "g_Id_click=278; dc_tos=s3egtp"
  url:
    user_article_url: "https://blog.csdn.net/community/home-api/v1/get-business-list" #获取用户文章接口
    is_collect_url: "https://blog.csdn.net/phoenix/web/v1/isCollect" #是否收藏接口
    add_collect_url: "https://mp-action.csdn.net/interact/wrapper/pc/favorite/v1/api/addFavoriteInFolds" #添加收藏接口
    is_comment_list_url: "https://blog.csdn.net/phoenix/web/v1/comment/list/"  #查询评论接口
    comment_url: "https://blog.csdn.net/phoenix/web/v1/comment/submit"  #评论接口
    like_url: "https://blog.csdn.net//phoenix/web/v1/article/like"  #点赞接口
    get_article_score_url: "https://bizapi.csdn.net/trends/api/v1/get-article-score"  #质量分接口